### ISSUE TITLE
Integrate PKI

### ISSUE THREAD

**Issue by davidlazar** [vuvuzela/vuvuzela#1]
Consider using [Keytree](https://github.com/jellevandenhooff/keytree) or [Keybase](https://keybase.io) as Vuvuzela's PKI.

**Comment by taoeffect** [comment]
Keeping your PKI options open is probably a good idea.

At [Rebooting Web of Trust](http://www.weboftrust.info/) we began work on what we're calling Decentralized PKI. We're just now finishing up a whitepaper on the subject. You may be interested in reviewing the [draft](https://docs.google.com/document/d/16ZE3FpTI2LteldyaSkvc1vvJHP3MyIt3ix-Lt9GxAqM/edit) and sending us feedback. Since it's still in its early days, now's a good time for feedback. :)

**Comment by taoeffect** [comment]
FYI, while I haven't analyzed Keytree in detail (only just now hearing of it thanks to you), I would question the use of Keybase in an anonymity focused project.

There are various potential issues:

- Most dangerous, Keybase is centralized. It is not an Internet standard as say, PKIX is, or DPKI aims to be. Its behavior can change arbitrarily at any point in time, potentially compromising any app that uses it.
- Keybase is centralized. Again, this means it's a central point of failure. If it goes down, your app becomes unusable.
- Keybase's security is effectively less than the security of X.509 PKIX (the standard DPKI aims to replace) because it adds additional points of failure. The security of X.509 PKIX [is laughable](https://lobste.rs/s/c4uiso/kazakhistan_to_mitm_all_ssl_traffic/comments/y6qxj9#c_y6qxj9).
- Keybase's Merkle commit things are signed by a key used by the developers. This is one key that needs to be compromised in order to render any Merkley things they do pointless for every public key in Keybase.

**Comment by taoeffect** [comment]
*Note to email readers: edited previous comment to add one additional issue with Keybase.*

**Comment by davidlazar** [comment]
Another issue is that Vuvuzela clients must be able to query the PKI privately, otherwise the queries leak metadata. One solution is to have every client mirror the PKI and query it locally.  Another solution is to use PIR for the queries.

**Comment by taoeffect** [comment]
Until you find a PKI to your satisfaction (and I hope it will be DPKI, once it's ready), consider doing the simple thing and using [Ricochet-style](https://ricochet.im/) identifiers.

**Comment by davidlazar** [comment]
For anyone watching, I recently submitted a paper on a new system that aims to solve the "PKI problem" for Vuvuzela.  I'll announce more details in the coming weeks.

**Comment by PowerPress** [comment]
Why not namecoin to handle the PKI? Its completely transparent and would allow users to verify the information themselves if using the namecoin client or use https://www.opennicproject.org/faq/ as DNS server to handle it for them transparently without a client.

Though https://blockstack.org/ may be another possibility.

**Comment by davidlazar** [comment]
We built [Alpenhorn](https://vuvuzela.io/alpenhorn-extended.pdf) to address this problem.

**Comment by davidlazar** [comment]
This has been solved by integrating Alpenhorn into Vuvuzela.

**Comment by taoeffect** [comment]
Hey, just wanna say congrats. Wish I had more time to review Alpenhorn properly, it looks like it has some trust-related tradeoffs, maybe you can more-better in-plain-English them in the docs or README?

**Comment by davidlazar** [comment]
Thanks!  I agree that we need a clear explanation of our assumptions.  I opened #21 to keep track of that.
